// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWmy_NbtkXicjPRv2w3mHk51jFB9qSueQ',
    appId: '1:16240396837:web:a561991fa5c0e381e2cdcc',
    messagingSenderId: '16240396837',
    projectId: 'loginapp-d4f91',
    authDomain: 'loginapp-d4f91.firebaseapp.com',
    storageBucket: 'loginapp-d4f91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClidb3U20kDCkbw78G0lGuvUtdUYJsjXA',
    appId: '1:16240396837:android:63596a1125408b0ee2cdcc',
    messagingSenderId: '16240396837',
    projectId: 'loginapp-d4f91',
    storageBucket: 'loginapp-d4f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0xKaFvXzj0YO2GT6HJiSFYMU_WDEFgwY',
    appId: '1:16240396837:ios:b68ca63bc56d623ae2cdcc',
    messagingSenderId: '16240396837',
    projectId: 'loginapp-d4f91',
    storageBucket: 'loginapp-d4f91.appspot.com',
    iosBundleId: 'com.example.girisyap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0xKaFvXzj0YO2GT6HJiSFYMU_WDEFgwY',
    appId: '1:16240396837:ios:b68ca63bc56d623ae2cdcc',
    messagingSenderId: '16240396837',
    projectId: 'loginapp-d4f91',
    storageBucket: 'loginapp-d4f91.appspot.com',
    iosBundleId: 'com.example.girisyap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWmy_NbtkXicjPRv2w3mHk51jFB9qSueQ',
    appId: '1:16240396837:web:613db3d1e56c4395e2cdcc',
    messagingSenderId: '16240396837',
    projectId: 'loginapp-d4f91',
    authDomain: 'loginapp-d4f91.firebaseapp.com',
    storageBucket: 'loginapp-d4f91.appspot.com',
  );
}
